tailwind.config = {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface-dim': '#d2d9f4',
                'primary-fixed-dim': '#b4c5ff',
                'inverse-primary': '#b4c5ff',
                'surface-container-highest': '#dae2fd',
                'on-tertiary': '#ffffff',
                surface: '#faf8ff',
                'on-primary-container': '#eeefff',
                'on-secondary': '#ffffff',
                'on-primary-fixed-variant': '#003ea8',
                'on-error-container': '#93000a',
                'primary-container': '#2563eb',
                'secondary-fixed': '#eaddff',
                error: '#ba1a1a',
                'surface-container-high': '#e2e7ff',
                'on-surface-variant': '#434655',
                'surface-bright': '#faf8ff',
                outline: '#737686',
                secondary: '#712ae2',
                'on-secondary-fixed-variant': '#5a00c6',
                'on-background': '#131b2e',
                'on-tertiary-container': '#efefff',
                'on-secondary-fixed': '#25005a',
                'tertiary-container': '#3761ea',
                'surface-container-lowest': '#ffffff',
                'on-primary': '#ffffff',
                primary: '#004ac6',
                'error-container': '#ffdad6',
                'inverse-on-surface': '#eef0ff',
                'on-tertiary-fixed-variant': '#0039b5',
                'surface-container-low': '#f2f3ff',
                'secondary-fixed-dim': '#d2bbff',
                tertiary: '#0d46d1',
                'secondary-container': '#8a4cfc',
                background: '#faf8ff',
                'surface-tint': '#0053db',
                'outline-variant': '#c3c6d7',
                'on-primary-fixed': '#00174b',
                'tertiary-fixed-dim': '#b7c4ff',
                'on-tertiary-fixed': '#001551',
                'surface-container': '#eaedff',
                'surface-variant': '#dae2fd',
                'on-surface': '#131b2e',
                'primary-fixed': '#dbe1ff',
                'tertiary-fixed': '#dce1ff',
                'on-secondary-container': '#fffbff',
                'inverse-surface': '#283044',
                'on-error': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                sm: '12px',
                xs: '4px',
                gutter: '24px',
                md: '24px',
                xl: '80px',
                'container-max': '1200px',
                lg: '48px',
                base: '8px',
            },
            fontFamily: {
                'headline-lg': ['Inter'],
                'body-lg': ['Inter'],
                'body-md': ['Inter'],
                'headline-xl': ['Inter'],
                'label-sm': ['Inter'],
                'label-md': ['Inter'],
                'headline-md': ['Inter'],
                'headline-xl-mobile': ['Inter'],
            },
            fontSize: {
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-xl': ['38px', { lineHeight: '50px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'headline-xl-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
            },
        },
    },
};
